version: '3.8'

services:
  web:
    image: jkuzn/segm_api-web:latest
    container_name: fastapi_app
    volumes:
      - ${DATA_VOLUME}:/DATA
      - ${RESULTS_VOLUME}:/RESULTS
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ON_GPU=${ON_GPU}
    shm_size: ${SHM_SIZE}
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    image: jkuzn/segm_api-celery_worker:latest
    container_name: celery_worker
    volumes:
      - ${DATA_VOLUME}:/DATA
      - ${RESULTS_VOLUME}:/RESULTS
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ON_GPU=${ON_GPU}
    shm_size: ${SHM_SIZE}

  redis:
    image: redis:6.2.14
    container_name: redis
    ports:
      - "6379:6379"
