version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    image: jkuzn/segm_api-web:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ${DATA_VOLUME}:/DATA
      - ${RESULTS_VOLUME}:/RESULTS
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ON_GPU=${ON_GPU}
      - results_ready_callback_url=${results_ready_callback_url}
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_DISABLE_REQUIRE=true
    shm_size: ${SHM_SIZE}
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    image: jkuzn/segm_api-celery_worker:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${DATA_VOLUME}:/DATA
      - ${RESULTS_VOLUME}:/RESULTS
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ON_GPU=${ON_GPU}
      - results_ready_callback_url=${results_ready_callback_url}
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_DISABLE_REQUIRE=true
    mem_limit: 60G
    memswap_limit: 76G
    shm_size: 32G
    ulimits:
      memlock: -1
      stack: 67108864
    depends_on:
      - redis

  redis:
    image: redis:6.2.14
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: