version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./DATA:/DATA
      - ./RESULTS:/RESULTS
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ON_GPU=FALSE # or TRUE, depending on your setup

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: ["/segm-api/start_celery.sh"]
    volumes:
      - ./DATA:/DATA
      - ./RESULTS:/RESULTS
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ON_GPU=FALSE # or TRUE, depending on your setup

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
